# Generated by Django 4.1.2 on 2022-10-23 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betrokkene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='betrokkene naam')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
            ],
            options={
                'verbose_name_plural': 'betrokkenen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Gemeente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='gemeente-naam')),
            ],
            options={
                'verbose_name_plural': 'gemeenten',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Grondslag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='grondslag naam')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
            ],
            options={
                'verbose_name_plural': 'grondslagen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Hoofdproces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='hoofdproces')),
            ],
            options={
                'verbose_name_plural': 'hoofdprocessen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Ontvanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='ontvanger')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
            ],
            options={
                'verbose_name_plural': 'ontvangers',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Persoonsgegeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type persoonsgegeven')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
            ],
            options={
                'verbose_name_plural': 'persoonsgegevens',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='teamnaam')),
            ],
            options={
                'verbose_name_plural': 'teams',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Verantwoordelijke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='verantwoordelijke')),
            ],
            options={
                'verbose_name_plural': 'verantwoordelijken',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Verordening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='verordening-naam')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
            ],
            options={
                'verbose_name_plural': 'verordeningen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Verwerker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='verwerker naam')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
            ],
            options={
                'verbose_name_plural': 'verwerkers',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Verwerking',
            fields=[
                ('naam', models.CharField(max_length=200, verbose_name='verwerkingsactiviteit')),
                ('doel', models.TextField(max_length=250, verbose_name='doel van verwerking')),
                ('reden_grondslag', models.TextField(blank=True, max_length=250, verbose_name='reden van grondslag')),
                ('bewaartermijn', models.CharField(max_length=200, verbose_name='bewaartermijn')),
                ('buitenEUgedeeld', models.BooleanField(default=False, verbose_name='buiten de EU gedeeld')),
                ('dpia_uitgevoerd', models.BooleanField(default=False, verbose_name='DPIA uitgevoerd')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
                ('betrokkenen', models.ManyToManyField(blank=True, related_name='verwerkingen', to='verwerkingen.betrokkene')),
                ('gemeente', models.ManyToManyField(blank=True, related_name='verwerkingen', to='verwerkingen.gemeente')),
                ('grondslag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verwerkingen', to='verwerkingen.grondslag')),
                ('hoofdproces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verwerkingen', to='verwerkingen.hoofdproces')),
                ('ontvangers', models.ManyToManyField(blank=True, related_name='verwerkingen', to='verwerkingen.ontvanger')),
                ('team', models.ManyToManyField(blank=True, to='verwerkingen.team')),
                ('verantwoordelijke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verwerkingen', to='verwerkingen.verantwoordelijke')),
                ('verordening', models.ManyToManyField(blank=True, related_name='verwerkingen', to='verwerkingen.verordening')),
                ('verwerkers', models.ManyToManyField(blank=True, related_name='verwerkingen', to='verwerkingen.verwerker')),
            ],
            options={
                'verbose_name_plural': 'verwerkingen',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='Verwerkersovereenkomst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='verwerkersovereenkomst naam')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
                ('pdf', models.FileField(blank=True, upload_to='documenten/verwerkingsovereenkomsten/')),
                ('vwo_start', models.DateField(blank=True, verbose_name='ingangsdatum verwerkersovereenkomst')),
                ('vwo_end', models.DateField(blank=True, verbose_name='einddatum verwerkersovereenkomst')),
                ('extern', models.BooleanField(default=False, verbose_name='Extern')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('start_at', models.DateField(auto_now=True, help_text='Start date of the record', verbose_name='start at')),
                ('end_at', models.DateField(blank=True, editable=False, help_text='End date of the record', null=True, verbose_name='end at')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of registration')),
                ('verwerker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verwerkersovereenkomsten', to='verwerkingen.verwerker')),
                ('verwerkingen', models.ManyToManyField(related_name='verwerkersovereenkomsten', to='verwerkingen.verwerking')),
            ],
            options={
                'verbose_name_plural': 'verwerkersovereenkomsten',
                'ordering': ['naam'],
            },
        ),
        migrations.AddField(
            model_name='betrokkene',
            name='persoonsgegevens',
            field=models.ManyToManyField(blank=True, related_name='betrokkenen', to='verwerkingen.persoonsgegeven'),
        ),
    ]
