# Generated by Django 4.1.2 on 2023-08-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Straat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='straatnaam')),
                ('gemeente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemeenten', to='geoworkflow.gemeente')),
            ],
            options={
                'verbose_name_plural': 'straten',
                'ordering': ['naam'],
            },
        ),
    ]
