# Generated by Django 4.1.2 on 2023-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0002_straat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAGgebeurtenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='BAGgebeurtenis')),
            ],
            options={
                'verbose_name_plural': 'BAGgebeurtenissen',
                'ordering': ['naam'],
            },
        ),
    ]
