# Generated by Django 4.1.2 on 2023-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0003_baggebeurtenis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baggebeurtenis',
            options={'ordering': ['naam'], 'verbose_name_plural': 'BAG gebeurtenissen'},
        ),
        migrations.AlterField(
            model_name='baggebeurtenis',
            name='naam',
            field=models.CharField(max_length=100, verbose_name='Baggebeurtenis'),
        ),
    ]
