# Generated by Django 4.1.2 on 2023-08-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0004_alter_baggebeurtenis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagobjecttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Bagobjecttype')),
            ],
            options={
                'verbose_name': 'BAG-objecttype',
                'verbose_name_plural': 'BAG objecttypen',
                'ordering': ['naam'],
            },
        ),
        migrations.AlterModelOptions(
            name='baggebeurtenis',
            options={'ordering': ['naam'], 'verbose_name': 'BAG-gebeurtenis', 'verbose_name_plural': 'BAG gebeurtenissen'},
        ),
        migrations.AddField(
            model_name='baggebeurtenis',
            name='bagobjecttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagobjecttypen', to='geoworkflow.bagobjecttype'),
        ),
    ]
