# Generated by Django 4.1.2 on 2023-08-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0005_bagobjecttype_alter_baggebeurtenis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagregistratie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokatieomschrijving', models.CharField(max_length=250, verbose_name='Lokatieomschrijving')),
                ('besluit', models.CharField(max_length=100, verbose_name='Lokatieomschrijving')),
                ('datum_besluit', models.DateField(blank=True, verbose_name='Datum besluit')),
                ('datum_ontvangst', models.DateField(blank=True, verbose_name='Datum ontvangst')),
                ('volledig_ontvangen', models.BooleanField(default=False, verbose_name='Volledig ontvangen')),
                ('juist_aangeleverd', models.BooleanField(default=False, verbose_name='Juist aangeleverd')),
                ('baggebeurtenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagregistraties', to='geoworkflow.baggebeurtenis')),
                ('bagobjecttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagregistraties', to='geoworkflow.bagobjecttype')),
                ('gemeente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagregistraties', to='geoworkflow.gemeente')),
                ('straat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bagregistraties', to='geoworkflow.straat')),
            ],
            options={
                'verbose_name': 'BAG-registratie',
                'verbose_name_plural': 'BAG registraties',
            },
        ),
    ]
