# Generated by Django 4.1.2 on 2023-09-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0006_bagregistratie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagregistratie',
            options={'ordering': ['datum_ontvangst'], 'verbose_name': 'BAG-registratie', 'verbose_name_plural': 'BAG registraties'},
        ),
        migrations.AlterModelOptions(
            name='gemeente',
            options={'ordering': ['naam'], 'verbose_name': 'gemeente', 'verbose_name_plural': 'gemeenten'},
        ),
        migrations.AlterModelOptions(
            name='straat',
            options={'ordering': ['naam'], 'verbose_name': 'straat', 'verbose_name_plural': 'straten'},
        ),
        migrations.AlterField(
            model_name='baggebeurtenis',
            name='bagobjecttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baggebeurtenissen', to='geoworkflow.bagobjecttype'),
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='besluit',
            field=models.CharField(blank=True, max_length=100, verbose_name='besluit'),
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='datum_besluit',
            field=models.DateField(blank=True, null=True, verbose_name='Datum besluit'),
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='datum_ontvangst',
            field=models.DateField(blank=True, null=True, verbose_name='Datum ontvangst'),
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='lokatieomschrijving',
            field=models.CharField(blank=True, max_length=250, verbose_name='Lokatieomschrijving'),
        ),
        migrations.AlterField(
            model_name='straat',
            name='gemeente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='straten', to='geoworkflow.gemeente'),
        ),
    ]
