# Generated by Django 4.1.2 on 2023-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0007_alter_bagregistratie_options_alter_gemeente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('registratie', models.CharField(choices=[('BAG administratie', 'Bag'), ('WOZ administratie', 'Woz'), ('GEO administratie', 'Geo')], max_length=100)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statussen',
            },
        ),
    ]
