# Generated by Django 4.1.2 on 2023-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0009_bagregistratie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagregistratie',
            name='tarief',
            field=models.CharField(choices=[('hoog', 'Hoog'), ('laag', 'Laag'), ('n.v.t.', 'Nvt')], default='NVT', max_length=50),
        ),
    ]
