# Generated by Django 4.1.2 on 2023-09-05 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geoworkflow', '0010_bagregistratie_tarief'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagregistratie',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagregistraties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notities', to=settings.AUTH_USER_MODEL)),
                ('baggebeurtenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notities', to='geoworkflow.bagregistratie')),
            ],
        ),
    ]
