# Generated by Django 4.1.2 on 2023-09-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0011_bagregistratie_author_notitie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='straat',
            unique_together={('gemeente', 'naam')},
        ),
    ]
