# Generated by Django 4.1.2 on 2023-09-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0012_alter_straat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='straat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='straat',
            constraint=models.UniqueConstraint(fields=('gemeente', 'naam'), name='unique straat'),
        ),
    ]
