# Generated by Django 4.1.2 on 2023-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0013_alter_straat_unique_together_straat_unique straat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gemeente',
            constraint=models.UniqueConstraint(fields=('naam', 'email'), name='unique gemeente'),
        ),
    ]
