# Generated by Django 4.1.2 on 2023-09-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0014_gemeente_unique gemeente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='straat',
            name='unique straat',
        ),
        migrations.AddConstraint(
            model_name='straat',
            constraint=models.UniqueConstraint(fields=('naam', 'gemeente'), name='unique straat'),
        ),
    ]
