# Generated by Django 4.1.2 on 2023-09-07 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0015_remove_straat_unique straat_straat_unique straat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagregistratie',
            name='lokatieomschrijving',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(message='Name should only consist of characters', regex='^[a-zA-Z]+$')], verbose_name='Lokatieomschrijving'),
        ),
    ]
