# Generated by Django 4.1.2 on 2023-09-07 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0016_alter_bagregistratie_lokatieomschrijving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagregistratie',
            name='besluit',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Gebruik alleen letters en cijfers. Geen speciale karakters', regex='^[a-zA-Z]+$')], verbose_name='besluit'),
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='lokatieomschrijving',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator(message='Gebruik alleen letters en cijfers. Geen speciale karakters', regex='^[a-zA-Z]+$')], verbose_name='Lokatieomschrijving'),
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='tarief',
            field=models.CharField(choices=[('hoog', 'Hoog'), ('laag', 'Laag'), ('n.v.t.', 'Nvt')], default='NVT', max_length=50, validators=[django.core.validators.RegexValidator(message='Gebruik alleen letters en cijfers. Geen speciale karakters', regex='^[a-zA-Z]+$')]),
        ),
    ]
