# Generated by Django 4.1.2 on 2023-09-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0018_alter_bagregistratie_besluit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notitie',
            old_name='baggebeurtenis',
            new_name='bagregistratie',
        ),
    ]
