# Generated by Django 4.1.2 on 2023-09-08 14:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0019_rename_baggebeurtenis_notitie_bagregistratie'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotitieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('type', models.CharField(max_length=100, verbose_name='Notitie Type')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
            ],
            options={
                'verbose_name': 'notitie-type',
                'verbose_name_plural': 'notitie types',
                'ordering': ['type'],
            },
        ),
        migrations.AlterField(
            model_name='bagregistratie',
            name='tarief',
            field=models.CharField(choices=[('hoog', 'Hoog'), ('laag', 'Laag'), ('n.v.t.', 'Nvt')], default='NVT', max_length=50),
        ),
        migrations.AddField(
            model_name='notitie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notities', to='geoworkflow.notitietype'),
        ),
    ]
