# Generated by Django 4.1.2 on 2023-09-11 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0020_notitietype_alter_bagregistratie_tarief_notitie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagregistratie',
            name='huisnummer',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Gebruik alleen letters en cijfers. Geen speciale karakters', regex='^[a-zA-Z, 0-9]+$')], verbose_name='Huisnummer'),
        ),
    ]
