# Generated by Django 4.1.2 on 2023-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoworkflow', '0021_bagregistratie_huisnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termijn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='termijnnaam')),
                ('termijn', models.IntegerField(blank=True, default=0, null=True, verbose_name='termijn in dagen')),
            ],
            options={
                'verbose_name': 'Termijn',
                'verbose_name_plural': 'Termijnen',
                'ordering': ['naam'],
            },
        ),
    ]
