# Generated by Django 4.1.2 on 2023-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='bron-naam')),
                ('beschrijving', models.TextField(blank=True, max_length=250, verbose_name='beschrijving')),
                ('url', models.URLField(max_length=100, verbose_name='URL (SLD.TLD)')),
            ],
            options={
                'verbose_name_plural': 'bronnen',
                'ordering': ['naam'],
            },
        ),
    ]
