# Generated by Django 4.1.2 on 2023-02-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waarmerken', '0007_zaakstatus'),
        ('bronnen', '0004_zaak_casemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaak',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zaken', to='waarmerken.zaakstatus'),
        ),
    ]
