# Generated by Django 4.1.2 on 2023-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronnen', '0005_zaak_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrokkene',
            name='huisnummer',
            field=models.IntegerField(blank=True, null=True, verbose_name='huisnummer'),
        ),
        migrations.AddField(
            model_name='betrokkene',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='postcode'),
        ),
    ]
