# Generated by Django 4.1.2 on 2023-02-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bronnen', '0006_betrokkene_huisnummer_betrokkene_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoekvraag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='zoekvraag-naam')),
                ('betrokkene', models.ForeignKey(blank=True, default='onbekend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoekvragen', to='bronnen.betrokkene')),
                ('bron', models.ManyToManyField(blank=True, related_name='zoekvragen', to='bronnen.bron')),
            ],
            options={
                'verbose_name_plural': 'zoekvragen',
                'ordering': ['naam'],
            },
        ),
    ]
