# Generated by Django 4.1.2 on 2022-12-20 16:04

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=200, verbose_name='documenttype')),
            ],
            options={
                'verbose_name_plural': 'Documenttypen',
            },
        ),
        migrations.CreateModel(
            name='Waarmerkniveau',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=200, verbose_name='waarmerkniveau')),
            ],
            options={
                'verbose_name_plural': 'Waarmerkniveaus',
            },
        ),
        migrations.CreateModel(
            name='Zaaktype',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=200, verbose_name='zaaktype')),
            ],
            options={
                'verbose_name_plural': 'Zaaktypen',
            },
        ),
        migrations.CreateModel(
            name='Documentwaarmerking',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=200, verbose_name='documentwaarmerking')),
                ('documenttype', models.ManyToManyField(related_name='documentwaarmerkingen', to='waarmerken.documenttype')),
                ('waarmerkniveau', models.ManyToManyField(related_name='documentwaarmerkingen', to='waarmerken.waarmerkniveau')),
                ('zaaktype', models.ManyToManyField(related_name='documentwaarmerkingen', to='waarmerken.zaaktype')),
            ],
            options={
                'verbose_name_plural': 'Document waarmerkingen',
            },
        ),
    ]
