# Generated by Django 4.1.2 on 2022-12-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waarmerken', '0002_remove_documentwaarmerking_naam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentwaarmerking',
            name='documenttype',
        ),
        migrations.RemoveField(
            model_name='documentwaarmerking',
            name='waarmerkniveau',
        ),
        migrations.RemoveField(
            model_name='documentwaarmerking',
            name='zaaktype',
        ),
        migrations.AddField(
            model_name='documentwaarmerking',
            name='documenttype',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.documenttype'),
        ),
        migrations.AddField(
            model_name='documentwaarmerking',
            name='waarmerkniveau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.waarmerkniveau'),
        ),
        migrations.AddField(
            model_name='documentwaarmerking',
            name='zaaktype',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.zaaktype'),
        ),
    ]
