# Generated by Django 4.1.2 on 2022-12-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waarmerken', '0003_remove_documentwaarmerking_documenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentwaarmerking',
            name='documenttype',
        ),
        migrations.RemoveField(
            model_name='documentwaarmerking',
            name='waarmerkniveau',
        ),
        migrations.RemoveField(
            model_name='documentwaarmerking',
            name='zaaktype',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.documentwaarmerking'),
        ),
        migrations.AddField(
            model_name='waarmerkniveau',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.documentwaarmerking'),
        ),
        migrations.AddField(
            model_name='zaaktype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.documentwaarmerking'),
        ),
    ]
