# Generated by Django 4.1.2 on 2022-12-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waarmerken', '0004_remove_documentwaarmerking_documenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='waarmerkniveau',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='zaaktype',
            name='type',
        ),
        migrations.AddField(
            model_name='documentwaarmerking',
            name='documenttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.documenttype'),
        ),
        migrations.AddField(
            model_name='documentwaarmerking',
            name='waarmerkniveai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.waarmerkniveau'),
        ),
        migrations.AddField(
            model_name='documentwaarmerking',
            name='zaaktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waarmerken.zaaktype'),
        ),
    ]
