# Generated by Django 4.1.2 on 2022-12-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waarmerken', '0005_remove_documenttype_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentwaarmerking',
            old_name='waarmerkniveai',
            new_name='waarmerkniveau',
        ),
    ]
