# Generated by Django 4.1.2 on 2023-02-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waarmerken', '0006_rename_waarmerkniveai_documentwaarmerking_waarmerkniveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaakstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='zaakstatus')),
                ('beschrijving', models.CharField(blank=True, max_length=200, verbose_name='beschrijving')),
            ],
            options={
                'verbose_name_plural': 'zaakstatussen',
                'ordering': ['naam'],
            },
        ),
    ]
