# Generated by Django 4.1.2 on 2022-11-07 14:27

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verwerkingattribuut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('naam', models.CharField(max_length=100, verbose_name='verwerkingattribuut')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'verwerkingsattributes',
                'ordering': ['naam'],
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='attribuut',
            field=models.ManyToManyField(blank=True, related_name='rollen', to='rechten.verwerkingattribuut'),
        ),
    ]
