# Generated by Django 4.1.2 on 2022-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0003_rolrecht_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolrecht',
            name='recht',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolrecht',
            name='naam',
            field=models.CharField(max_length=100, verbose_name='rol'),
        ),
    ]
