# Generated by Django 4.1.2 on 2022-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0005_rol_delete_rolrecht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='attribuut',
            new_name='attributes',
        ),
        migrations.AlterField(
            model_name='verwerkingattribuut',
            name='naam',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
