# Generated by Django 4.1.2 on 2022-11-07 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0006_rename_attribuut_rol_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id',
        ),
        migrations.AlterField(
            model_name='rol',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False, unique=True),
        ),
    ]
