# Generated by Django 4.1.2 on 2022-11-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0007_remove_rol_id_alter_rol_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='attributes',
            new_name='attributesa',
        ),
    ]
