# Generated by Django 4.1.2 on 2022-11-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0008_rename_attributes_rol_attributesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='attributesa',
            new_name='attributes',
        ),
    ]
