# Generated by Django 4.1.2 on 2022-11-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0010_verwerkingattribuut_publiceren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verwerkingattribuut',
            name='publiceren',
        ),
    ]
