# Generated by Django 4.1.2 on 2022-11-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0012_publiceerattribuut'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiceerattribuut',
            name='publiceer',
            field=models.BooleanField(default=False),
        ),
    ]
