# Generated by Django 4.1.2 on 2022-11-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechten', '0013_publiceerattribuut_publiceer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='attributes',
        ),
    ]
