# Generated by Django 4.1.2 on 2022-12-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algoritme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='algoritme',
            name='title',
        ),
    ]
